// Copyright 2017-2022 @alt-research/dev authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @alt-research/dev

export const packageInfo = { name: '@alt-research/dev', path: 'auto', type: 'auto', version: '0.0.2' };
